# Generated by Django 6.1 on 2026-08-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicines_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
