# Generated by Django 6.1 on 2026-08-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_email_alter_customers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='purchases',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
