# Generated by Django 6.1 on 2026-09-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customers_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='purchases',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
